version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: mrtorrent
      POSTGRES_PASSWORD: mrt0rr3n7
      POSTGRES_DB: mr_torrent_dev
    ports: ["5432:5432"]
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
